[project]
name = "TeamKUNPluginManager"
short_name = "KPM"
url = "https//github.com/TeamKun/{project.name}"

[project.version]
name = "v2.8.3"
url = "{project.url}/releases/tag/{project.version.name}"

[project.license]
name = "The MIT License"
url = "{project.url}/blob/LICENSE"
