name: CI

on:
  push:
    branches:
      - production
      - develop
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build with Node.js
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  lint:
    name: Lint with Node.js 16, ubuntu-latest
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint:sarif
      - name: Upload lint results to GitHub repository
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
      - name: Check formatting
        run: npm run check:format
