name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - production

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub Deployment
        id: deploy-status
        with:
          token: ${{ github.token }}
          environment-url: https://kpm.kunlab.org
          environment: production
          status: in_progress

      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
      - name: Update GitHub Deployment
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          deployment-id: ${{ steps.deploy-status.outputs.deployment_id }}
          state: success
          environment-url: https://kpm.kunlab.org
          environment: production
      - name: Update GitHub Deployment
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          deployment-id: ${{ steps.deploy-status.outputs.deployment_id }}
          state: failure
          environment-url: https://kpm.kunlab.org
      - name: Update GitHub Deployment
        if: cancelled()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          deployment-id: ${{ steps.deploy-status.outputs.deployment_id }}
          state: cancelled
          environment-url: https://kpm.kunlab.org
